spring:
  application:
    name: restaurant-api
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:mysql://restaurantdb:3306/restaurantdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    password: restaurantdbUser
    username: restaurantdPassword
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
